version: "3.8"

services:
  web:
    image: mimacom-task:web
    build:
      dockerfile: Dockerfile
      context: .
      target: prod
      args:
        - API_URL=http://localhost:5001
    ports:
      - 5000:80
  api:
    image: mimacom-task:api
    build:
      dockerfile: Dockerfile.api
      context: .
    ports:
      - 5001:3000

