FROM node:18.19.0-alpine3.18 as prod
RUN mkdir /app && chown -R node:node /app
WORKDIR /app
RUN npm install -g json-server
COPY --chown=node:node .docker/server-api ./
EXPOSE 3000
USER node
CMD ["json-server", "-H", "0.0.0.0", "/app/db.json"]
