name: Api Image Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths: 
      - .github/workflows/api.build.yml

jobs:
  build-image-and-push:
    uses: ./.github/workflows/build.base.yml
    secrets: inherit
    permissions:
      packages: write
    with:
      version: 0.0.1
      imagename: mimacom-challenge-api
      imagesfile: Dockerfile.api